# Generated by Django 2.2.16 on 2022-05-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220506_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
